### ISSUE TITLE
recursive_merge_dicts (two issues)

### ISSUE THREAD

**Issue by mireianievas** [chaimain/asgardpy#140]
* First issue in that function from config/generator.py (l109):

final_copy = base_config.copy() -> there seems to be no copy() definition there. I bypassed this error by using copy(base_config), however, it fails at the next point:

```
File ~/Software/asgardpy/src/asgardpy/config/generator.py:109, in recursive_merge_dicts(base_config, extra_config)
    107 from copy import copy
    108 final_config = copy(base_config)
--> 109 for key, value in extra_config.items():
    110     if key in final_config and isinstance(final_config[key], list):
    111         new_config = []

AttributeError: 'AnalysisStepEnum' object has no attribute 'items'
```

### Versions

python 3.11

**Comment by mireianievas** [comment]
the parent call that leads to this error is 

`
dataset_3d.py:531    self.config_full.update(self.config_full)
`

what is this supposed to do anyway

**Comment by chaimain** [comment]
The function is `update_source_pos_from_3d_dataset`, where the sky position of the target source, can be updated from the spatial model information in the list of sources of the 3D Dataset (for eg. XML models for Fermi-LAT), in the `AsgardpyConfig.target.sky_position` value.

The `self.config_full.update(self.config_full)` is to update the initialized `self.config_full` `AsgardpyConfig` object with the updated parameters.

I think the errors come due to some incorrect initialization of `self.config_full` in the calling of `Dataset3DGeneration`, which should be an `AsgardpyConfig` object and not an `AnalysisStepEnum` one. This is called in the line https://github.com/chaimain/asgardpy/blob/main/src/asgardpy/data/dataset_3d.py#L152 where `self.config` is passed to be initialized as `self.config_full` in the `Dataset3DGeneration` call.

This is most likely connected to the other issue we discussed privately, regarding using `AsgardpyConfig` yaml files to initiate this object.

**Comment by chaimain** [comment]
Although, it is slightly different from the issues mentioned here, I noted a bug in the case of updating the model config, for example, from 4 parameters to 6 parameters (BPL -> SBPL). #143 will fix that, after which I will close this issue.
